### ISSUE TITLE
No one cares, right? Create an issue to express support.

### ISSUE THREAD

**Issue by huangguifeng** [AIRI-Institute/HairFastGAN#1]
No one cares, right? Create an issue to express support. Not sure how it will perform, will give it a try later to see if it can run.

**Comment by SShirot** [comment]
can you guide me step-by-step training with this ? Indeed, I want to train by my data with this model

**Comment by maximkm** [comment]
> can you guide me step-by-step training with this ? Indeed, I want to train by my data with this model

Hello, @SShirot!

This question has already been addressed in a neighboring thread: [Issue #3](https://github.com/AIRI-Institute/HairFastGAN/issues/3). Please take a look there for a step-by-step guide.

If you have any further questions or need additional help, feel free to ask!
