### ISSUE TITLE
There are some questions regarding the PostProcess module

### ISSUE THREAD

**Issue by BiiiGerrr** [AIRI-Institute/HairFastGAN#2]
Regarding the latent_avg.pt weights, how should I obtain Savg?

**Comment by maximkm** [comment]
Hello!

The average latent (`Savg`) is loaded directly in the code, which you can see here: [Encoders.py, Line 112](https://github.com/AIRI-Institute/HairFastGAN/blob/b34c596d0722ec050412cb7245005a678fe68be5/models/Encoders.py#L112).

You can download the corresponding weights (`latent_avg.pt`) from this link: [latent_avg.pt on Hugging Face](https://huggingface.co/AIRI-Institute/HairFastGAN/blob/main/pretrained_models/PostProcess/latent_avg.pt).

### How `Savg` Was Computed:

Initially, these latents were computed using a pre-trained FS encoder. We inverted real images from the FFHQ dataset and averaged the resulting `S` latents.

If you were asking about something else or have additional questions, feel free to let me know!
