### ISSUE TITLE
Training process ?

### ISSUE THREAD

**Issue by sahilshukla3003** [AIRI-Institute/HairFastGAN#3]
Can you describe about the training process , how can one train this for there own dataset...?

**Comment by maximkm** [comment]
Hello!

Our pipeline consists of **three models** that you can train on your own dataset:

1. **Rotate Encoder**
2. **Color Encoder**
3. **Refinement Encoder**

### **Training Process Overview**

#### **1. Data Preprocessing**

Before training each model, you need to preprocess your data using the corresponding scripts:

- **Rotate Encoder:**  
  `scripts/rotate_gen.py`

- **Color Encoder:**  
  `scripts/blending_gen.py`

- **Refinement Encoder:**  
  `scripts/pp_gen.py`

**Usage Example:**
```bash
python scripts/rotate_gen.py --FFHQ /path/to/your/dataset --size 256
python scripts/blending_gen.py --FFHQ /path/to/your/dataset --size 256
python scripts/pp_gen.py --FFHQ /path/to/your/dataset --size 256
```
- **`--FFHQ`**: Specify the path to your image dataset.
- **`--size`**: (Optional) Reduce the size if you have limited resources.

#### **2. Training the Models**

After preprocessing, run the training scripts for each encoder:

- **Rotate Encoder:**  
  `scripts/rotate_train.py`

- **Color Encoder:**  
  `scripts/blending_train.py`

- **Refinement Encoder:**  
  `scripts/pp_train.py`

**Usage Example:**
```bash
python scripts/rotate_train.py --FFHQ /path/to/your/dataset --fid_dataset /path/to/fid/dataset
python scripts/blending_train.py --FFHQ /path/to/your/dataset --fid_dataset /path/to/fid/dataset
python scripts/pp_train.py --FFHQ /path/to/your/dataset --fid_dataset /path/to/fid/dataset
```
- **`--FFHQ`**: Path to your training dataset.
- **`--fid_dataset`**: Path to the dataset used for measuring FID metrics during evaluation.

---

All preprocessing and training scripts have a similar interface, making it easy to switch between models.

If you have any additional questions or concerns, don't hesitate to ask!

**Comment by sahilshukla3003** [comment]
If I trained it on long hair dataset beyond align faces will it work
