### ISSUE TITLE
can I enlarge the face recognition area?

### ISSUE THREAD

**Issue by ywythu** [AIRI-Institute/HairFastGAN#4]
I noticed that the face recognition area is square, but if the hair is long, part of it gets cut off. Can the recognition area be enlarged in such cases?

**Comment by maximkm** [comment]
Hello,

Unfortunately, StyleGAN is trained on aligned faces, and our method operates within the StyleGAN space, which requires cropping the face before changing the hairstyle.

Expanding StyleGAN to handle unaligned images is a complex task that would need additional research and integration. Some existing work addresses this, such as [this paper](https://arxiv.org/abs/2303.06146).

Additionally, face alignment is an irreversible process. However, our other work has attempted to reverse it. If the new hairstyle is short, you might try automatically pasting it into the original uncropped image. You can find the relevant code [here](https://github.com/AIRI-Institute/StyleFeatureEditor/blob/c9808a512ff660c310ea17f4a9e7d0c98b6e6c35/runners/simple_runner.py#L74C13-L74C25).

**Comment by ywythu** [comment]
> Hello,
> 
> Unfortunately, StyleGAN is trained on aligned faces, and our method operates within the StyleGAN space, which requires cropping the face before changing the hairstyle.
> 
> Expanding StyleGAN to handle unaligned images is a complex task that would need additional research and integration. Some existing work addresses this, such as [this paper](https://arxiv.org/abs/2303.06146).
> 
> Additionally, face alignment is an irreversible process. However, our other work has attempted to reverse it. If the new hairstyle is short, you might try automatically pasting it into the original uncropped image. You can find the relevant code [here](https://github.com/AIRI-Institute/StyleFeatureEditor/blob/c9808a512ff660c310ea17f4a9e7d0c98b6e6c35/runners/simple_runner.py#L74C13-L74C25).

thanks for your reply, but what I mean is not inference on unaligned face, I only want to enlarge the aligned face region because sometimes the hair in aligned face may be out of the region and not influenced by the model. So I wonder if it's possible to just enlarged the aligned region to put the whole hair image into the model

**Comment by oekara** [comment]
Hi, were you able to figure out how you can utilize the current codebase for longer hairs. I guess some parameters have to change, but I couldn't find.
